name: AtMessage
version: 1.0.7
description: AtMessage is a new way to whisper
author: Th3Shadowbroker
website: http://crafter629.de
main: com.th3shadowbroker.AtMessage.main
load: POSTWORLD

commands:
     amsg:
        description: Reload config or get the installed version
        usage: '/amsg [reload]'
        permission: AMsg.admin
     spectate:
         description: Spectate other players AtMessage conversations
         usage: '/spectate'
         aliases: [spec, spy]
         permission: AMsg.spectate